name: Daily Job

on:
  schedule:
    # Run the workflow every day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This job runs daily at 12:00 UTC!"
